// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Service) Close() {
	_m.Called()
}

// Send provides a mock function with given fields: message
func (_m *Service) Send(message string) {
	//_m.Called(message)
}
